---
abstract: "Exceptions that don't hurt."
author:
  - 'JT Smith <jt@plainblack.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Ouch
resources:
  bugtracker: http://github.com/rizen/Ouch/issues
  repository: git://github.com/rizen/Ouch.git
version: 0.0200
